# Generated by Django 5.2 on 2025-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0002_user_admin_user_user_session_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='coins_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='coins_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='highest_turn',
            field=models.IntegerField(default=0),
        ),
    ]
