# Generated by Django 5.2 on 2025-04-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
