# Generated by Django 5.2 on 2025-04-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0006_remove_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('coins_a', models.IntegerField(default=0)),
                ('coins_b', models.IntegerField(default=0)),
                ('turn_number', models.IntegerField(default=0)),
                ('current_turn', models.CharField(choices=[('PARTY_A', 'Party A'), ('PARTY_B', 'Party B')], default='PARTY_A', max_length=16)),
                ('activity_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_id', to='custom_app.user')),
                ('party_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_a', to='custom_app.user')),
                ('party_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_b', to='custom_app.user')),
            ],
        ),
    ]
