# Generated by Django 5.2 on 2025-04-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0007_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='custom_app.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='party_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_a', to='custom_app.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='party_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_b', to='custom_app.user'),
        ),
    ]
