# Generated by Django 5.2 on 2025-04-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0008_game_active_alter_game_creator_id_alter_game_party_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
