# Generated by Django 5.2 on 2025-04-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0009_rename_creator_id_game_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_stage',
            field=models.CharField(choices=[('PICKING', 'Picking word'), ('DRAWING', 'Drawing word'), ('GUESSING', 'Guessing word')], default='PICKING', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='word',
            field=models.CharField(default='invalid', max_length=32),
        ),
    ]
