# Generated by Django 5.2 on 2025-04-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0010_game_difficulty_game_turn_stage_game_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='choice_easy',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='game',
            name='choice_hard',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='game',
            name='choice_medium',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='word',
            field=models.CharField(default='', max_length=32),
        ),
    ]
