# Generated by Django 5.2 on 2025-04-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0011_game_choice_easy_game_choice_hard_game_choice_medium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('recording_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=256, null=True)),
                ('turn_number', models.IntegerField(default=0)),
                ('drawn_word', models.CharField(max_length=32)),
                ('word_difficulty', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='custom_app.game')),
            ],
        ),
    ]
