# Generated by Django 5.2 on 2025-04-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0012_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rounds_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn_number',
            field=models.IntegerField(default=1),
        ),
    ]
