# Generated by Django 5.2 on 2025-05-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0013_user_games_played_user_rounds_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorBundle',
            fields=[
                ('bundle_id', models.AutoField(primary_key=True, serialize=False)),
                ('rarity', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('rarity', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('g', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='custom_app.colorbundle')),
            ],
        ),
    ]
