# Generated by Django 5.2 on 2025-05-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0014_colorbundle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorbundle',
            name='price',
            field=models.IntegerField(default=999999),
        ),
        migrations.AlterField(
            model_name='color',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='custom_app.colorbundle'),
        ),
    ]
