# Generated by Django 5.2 on 2025-06-03 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0016_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColorBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_price', models.IntegerField()),
                ('color_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by', to='custom_app.colorbundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_bundles', to='custom_app.user')),
            ],
            options={
                'unique_together': {('user', 'color_bundle')},
            },
        ),
    ]
