# Generated by Django 5.2 on 2025-06-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0018_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recording',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
    ]
