# Generated by Django 5.2 on 2025-06-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0019_game_current_attempt_recording_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bombs',
            field=models.IntegerField(default=0),
        ),
    ]
